// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudWkt

/// An accelerator configuration for a VM instance
/// Definition of a hardware accelerator. Note that there is no check on `type`
/// and `core_count` combinations. TPUs are not supported.
/// See [GPUs on Compute
/// Engine](https://cloud.google.com/compute/docs/gpus/#gpus-list) to find a
/// valid combination.
public struct AcceleratorConfig: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// Optional. Type of this accelerator.
  public var type: AcceleratorConfig.AcceleratorType = AcceleratorConfig.AcceleratorType()

  /// Optional. Count of cores of this accelerator.
  public var coreCount: Swift.Int64 = Swift.Int64()

  /// Initialize a new instance of `AcceleratorConfig`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = AcceleratorConfig().with { $0.type = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  /// Definition of the types of hardware accelerators that can be used on
  /// this instance.
  public enum AcceleratorType: Codable, Equatable, Sendable {
    /// Accelerator type is not specified.
    case unspecified
    /// Accelerator type is Nvidia Tesla P100.
    case nvidiaTeslaP100
    /// Accelerator type is Nvidia Tesla V100.
    case nvidiaTeslaV100
    /// Accelerator type is Nvidia Tesla P4.
    case nvidiaTeslaP4
    /// Accelerator type is Nvidia Tesla T4.
    case nvidiaTeslaT4
    /// Accelerator type is NVIDIA Tesla T4 Virtual Workstations.
    case nvidiaTeslaT4Vws
    /// Accelerator type is NVIDIA Tesla P100 Virtual Workstations.
    case nvidiaTeslaP100Vws
    /// Accelerator type is NVIDIA Tesla P4 Virtual Workstations.
    case nvidiaTeslaP4Vws
    /// Accelerator type is Nvidia Tesla A100 - 40GB.
    case nvidiaTeslaA100
    /// Accelerator type is Nvidia Tesla A100 - 80GB.
    case nvidiaA10080Gb
    /// Accelerator type is Nvidia Tesla L4.
    case nvidiaL4
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownStringValue(String)

    public init() {
      self = .unspecified
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .unspecified: return 0
      case .nvidiaTeslaP100: return 2
      case .nvidiaTeslaV100: return 3
      case .nvidiaTeslaP4: return 4
      case .nvidiaTeslaT4: return 5
      case .nvidiaTeslaT4Vws: return 8
      case .nvidiaTeslaP100Vws: return 9
      case .nvidiaTeslaP4Vws: return 10
      case .nvidiaTeslaA100: return 11
      case .nvidiaA10080Gb: return 12
      case .nvidiaL4: return 13
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: Swift.String? {
      switch self {
      case .unspecified: return "ACCELERATOR_TYPE_UNSPECIFIED"
      case .nvidiaTeslaP100: return "NVIDIA_TESLA_P100"
      case .nvidiaTeslaV100: return "NVIDIA_TESLA_V100"
      case .nvidiaTeslaP4: return "NVIDIA_TESLA_P4"
      case .nvidiaTeslaT4: return "NVIDIA_TESLA_T4"
      case .nvidiaTeslaT4Vws: return "NVIDIA_TESLA_T4_VWS"
      case .nvidiaTeslaP100Vws: return "NVIDIA_TESLA_P100_VWS"
      case .nvidiaTeslaP4Vws: return "NVIDIA_TESLA_P4_VWS"
      case .nvidiaTeslaA100: return "NVIDIA_TESLA_A100"
      case .nvidiaA10080Gb: return "NVIDIA_A100_80GB"
      case .nvidiaL4: return "NVIDIA_L4"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to ``.unknownStringValue(_:)``.
    public init(stringValue: Swift.String) {
      switch stringValue {
      case "ACCELERATOR_TYPE_UNSPECIFIED": self = .unspecified
      case "NVIDIA_TESLA_P100": self = .nvidiaTeslaP100
      case "NVIDIA_TESLA_V100": self = .nvidiaTeslaV100
      case "NVIDIA_TESLA_P4": self = .nvidiaTeslaP4
      case "NVIDIA_TESLA_T4": self = .nvidiaTeslaT4
      case "NVIDIA_TESLA_A100": self = .nvidiaTeslaA100
      case "NVIDIA_A100_80GB": self = .nvidiaA10080Gb
      case "NVIDIA_L4": self = .nvidiaL4
      case "NVIDIA_TESLA_T4_VWS": self = .nvidiaTeslaT4Vws
      case "NVIDIA_TESLA_P100_VWS": self = .nvidiaTeslaP100Vws
      case "NVIDIA_TESLA_P4_VWS": self = .nvidiaTeslaP4Vws
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to ``.unknownIntValue(_:)``.
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .unspecified
      case 2: self = .nvidiaTeslaP100
      case 3: self = .nvidiaTeslaV100
      case 4: self = .nvidiaTeslaP4
      case 5: self = .nvidiaTeslaT4
      case 8: self = .nvidiaTeslaT4Vws
      case 9: self = .nvidiaTeslaP100Vws
      case 10: self = .nvidiaTeslaP4Vws
      case 11: self = .nvidiaTeslaA100
      case 12: self = .nvidiaA10080Gb
      case 13: self = .nvidiaL4
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .unspecified: return try container.encode(0)
      case .nvidiaTeslaP100: return try container.encode(2)
      case .nvidiaTeslaV100: return try container.encode(3)
      case .nvidiaTeslaP4: return try container.encode(4)
      case .nvidiaTeslaT4: return try container.encode(5)
      case .nvidiaTeslaT4Vws: return try container.encode(8)
      case .nvidiaTeslaP100Vws: return try container.encode(9)
      case .nvidiaTeslaP4Vws: return try container.encode(10)
      case .nvidiaTeslaA100: return try container.encode(11)
      case .nvidiaA10080Gb: return try container.encode(12)
      case .nvidiaL4: return try container.encode(13)
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.notebooks.v2.AcceleratorConfig"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
