// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWKT

/// The definition of a boot disk.
public struct BootDisk: Codable, Equatable, GoogleCloudWKT._AnyPackable,
  Sendable
{
  /// Optional. The size of the boot disk in GB attached to this instance, up to
  /// a maximum of 64000 GB (64 TB). If not specified, this defaults to the
  /// recommended value of 150GB.
  public var diskSizeGb: Swift.Int64 = Swift.Int64()

  /// Optional. Indicates the type of the disk.
  public var diskType: DiskType = DiskType()

  /// Optional. Input only. Disk encryption method used on the boot and data
  /// disks, defaults to GMEK.
  public var diskEncryption: DiskEncryption = DiskEncryption()

  /// Optional. Input only. The KMS key used to encrypt the disks, only
  /// applicable if disk_encryption is CMEK. Format:
  /// `projects/{project_id}/locations/{location}/keyRings/{key_ring_id}/cryptoKeys/{key_id}`
  ///
  /// Learn more about using your own encryption keys.
  public var kmsKey: Swift.String = Swift.String()

  /// Initialize a new instance of `BootDisk`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = BootDisk().with { $0.diskSizeGb = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.notebooks.v2.BootDisk"
  }
  public init(fromAny any: GoogleCloudWKT.`Any`) throws {
    self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWKT.Struct {
    return try GoogleCloudWKT._slowAnySerialize(message: self)
  }
}
