// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleWKT

/// Response for checking if a notebook instance is upgradeable.
public struct CheckInstanceUpgradabilityResponse: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// If an instance is upgradeable.
  public var upgradeable: Swift.Bool = Swift.Bool()

  /// The version this instance will be upgraded to if calling the upgrade
  /// endpoint. This field will only be populated if field upgradeable is true.
  public var upgradeVersion: Swift.String = Swift.String()

  /// Additional information about upgrade.
  public var upgradeInfo: Swift.String = Swift.String()

  /// The new image self link this instance will be upgraded to if calling the
  /// upgrade endpoint. This field will only be populated if field upgradeable
  /// is true.
  public var upgradeImage: Swift.String = Swift.String()

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `CheckInstanceUpgradabilityResponse`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = CheckInstanceUpgradabilityResponse().with { $0.upgradeable = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let upgradeable = CodingKeys(stringValue: "upgradeable")
    static let upgradeVersion = CodingKeys(stringValue: "upgradeVersion")
    static let upgradeInfo = CodingKeys(stringValue: "upgradeInfo")
    static let upgradeImage = CodingKeys(stringValue: "upgradeImage")

    static let _knownKeys: Set<Swift.String> = [
      "upgradeable",
      "upgradeVersion",
      "upgradeInfo",
      "upgradeImage",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(Swift.Bool.self, forKey: .upgradeable) {
      self.upgradeable = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .upgradeVersion) {
      self.upgradeVersion = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .upgradeInfo) {
      self.upgradeInfo = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .upgradeImage) {
      self.upgradeImage = value
    }
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.Value.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.upgradeable, forKey: .upgradeable)
    try container.encode(self.upgradeVersion, forKey: .upgradeVersion)
    try container.encode(self.upgradeInfo, forKey: .upgradeInfo)
    try container.encode(self.upgradeImage, forKey: .upgradeImage)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.notebooks.v2.CheckInstanceUpgradabilityResponse"
  }
  public init(fromAny any: GoogleWKT.`Any`) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.Struct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
