// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) public import GoogleWKT

/// An instance-attached disk resource.
public struct DataDisk: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// Optional. The size of the disk in GB attached to this VM instance, up to a
  /// maximum of 64000 GB (64 TB). If not specified, this defaults to 100.
  public var diskSizeGb: Swift.Int64 = Swift.Int64()

  /// Optional. Input only. Indicates the type of the disk.
  public var diskType: DiskType = DiskType()

  /// Optional. Input only. Disk encryption method used on the boot and data
  /// disks, defaults to GMEK.
  public var diskEncryption: DiskEncryption = DiskEncryption()

  /// Optional. Input only. The KMS key used to encrypt the disks, only
  /// applicable if disk_encryption is CMEK. Format:
  /// `projects/{project_id}/locations/{location}/keyRings/{key_ring_id}/cryptoKeys/{key_id}`
  ///
  /// Learn more about using your own encryption keys.
  public var kmsKey: Swift.String = Swift.String()

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `DataDisk`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = DataDisk().with { $0.diskSizeGb = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let diskSizeGb = CodingKeys(stringValue: "diskSizeGb")
    static let diskType = CodingKeys(stringValue: "diskType")
    static let diskEncryption = CodingKeys(stringValue: "diskEncryption")
    static let kmsKey = CodingKeys(stringValue: "kmsKey")

    static let _knownKeys: Set<Swift.String> = [
      "diskSizeGb",
      "diskType",
      "diskEncryption",
      "kmsKey",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(Swift.Int64.self, forKey: .diskSizeGb) {
      self.diskSizeGb = value
    }
    if let value = try container.decodeIfPresent(DiskType.self, forKey: .diskType) {
      self.diskType = value
    }
    if let value = try container.decodeIfPresent(DiskEncryption.self, forKey: .diskEncryption) {
      self.diskEncryption = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .kmsKey) {
      self.kmsKey = value
    }
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.WKTValue.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.diskSizeGb, forKey: .diskSizeGb)
    try container.encode(self.diskType, forKey: .diskType)
    try container.encode(self.diskEncryption, forKey: .diskEncryption)
    try container.encode(self.kmsKey, forKey: .kmsKey)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.notebooks.v2.DataDisk"
  }
  public init(fromAny any: GoogleWKT.WKTAny) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.WKTStruct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
