// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWkt

/// Defines flags that are used to run the diagnostic tool
public struct DiagnosticConfig: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// Required. User Cloud Storage bucket location (REQUIRED).
  /// Must be formatted with path prefix (`gs://$GCS_BUCKET`).
  ///
  /// Permissions:
  /// User Managed Notebooks:
  /// - storage.buckets.writer: Must be given to the project's service account
  ///   attached to VM.
  /// Google Managed Notebooks:
  /// - storage.buckets.writer: Must be given to the project's service account or
  ///   user credentials attached to VM depending on authentication mode.
  ///
  /// Cloud Storage bucket Log file will be written to
  /// `gs://$GCS_BUCKET/$RELATIVE_PATH/$VM_DATE_$TIME.tar.gz`
  public var gcsBucket: Swift.String = Swift.String()

  /// Optional. Defines the relative storage path in the Cloud Storage bucket
  /// where the diagnostic logs will be written: Default path will be the root
  /// directory of the Cloud Storage bucket
  /// (`gs://$GCS_BUCKET/$DATE_$TIME.tar.gz`) Example of full path where Log file
  /// will be written: `gs://$GCS_BUCKET/$RELATIVE_PATH/`
  public var relativePath: Swift.String = Swift.String()

  /// Optional. Enables flag to repair service for instance
  public var enableRepairFlag: Swift.Bool = Swift.Bool()

  /// Optional. Enables flag to capture packets from the instance for 30 seconds
  public var enablePacketCaptureFlag: Swift.Bool = Swift.Bool()

  /// Optional. Enables flag to copy all `/home/jupyter` folder contents
  public var enableCopyHomeFilesFlag: Swift.Bool = Swift.Bool()

  /// Initialize a new instance of `DiagnosticConfig`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = DiagnosticConfig().with { $0.gcsBucket = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.notebooks.v2.DiagnosticConfig"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
