// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) public import GoogleWKT

/// Defines flags that are used to run the diagnostic tool
public struct DiagnosticConfig: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// Required. User Cloud Storage bucket location (REQUIRED).
  /// Must be formatted with path prefix (`gs://$GCS_BUCKET`).
  ///
  /// Permissions:
  /// User Managed Notebooks:
  /// - storage.buckets.writer: Must be given to the project's service account
  ///   attached to VM.
  /// Google Managed Notebooks:
  /// - storage.buckets.writer: Must be given to the project's service account or
  ///   user credentials attached to VM depending on authentication mode.
  ///
  /// Cloud Storage bucket Log file will be written to
  /// `gs://$GCS_BUCKET/$RELATIVE_PATH/$VM_DATE_$TIME.tar.gz`
  public var gcsBucket: Swift.String = Swift.String()

  /// Optional. Defines the relative storage path in the Cloud Storage bucket
  /// where the diagnostic logs will be written: Default path will be the root
  /// directory of the Cloud Storage bucket
  /// (`gs://$GCS_BUCKET/$DATE_$TIME.tar.gz`) Example of full path where Log file
  /// will be written: `gs://$GCS_BUCKET/$RELATIVE_PATH/`
  public var relativePath: Swift.String = Swift.String()

  /// Optional. Enables flag to repair service for instance
  public var enableRepairFlag: Swift.Bool = Swift.Bool()

  /// Optional. Enables flag to capture packets from the instance for 30 seconds
  public var enablePacketCaptureFlag: Swift.Bool = Swift.Bool()

  /// Optional. Enables flag to copy all `/home/jupyter` folder contents
  public var enableCopyHomeFilesFlag: Swift.Bool = Swift.Bool()

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `DiagnosticConfig`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = DiagnosticConfig().with { $0.gcsBucket = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let gcsBucket = CodingKeys(stringValue: "gcsBucket")
    static let relativePath = CodingKeys(stringValue: "relativePath")
    static let enableRepairFlag = CodingKeys(stringValue: "enableRepairFlag")
    static let enablePacketCaptureFlag = CodingKeys(stringValue: "enablePacketCaptureFlag")
    static let enableCopyHomeFilesFlag = CodingKeys(stringValue: "enableCopyHomeFilesFlag")

    static let _knownKeys: Set<Swift.String> = [
      "gcsBucket",
      "relativePath",
      "enableRepairFlag",
      "enablePacketCaptureFlag",
      "enableCopyHomeFilesFlag",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .gcsBucket) {
      self.gcsBucket = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .relativePath) {
      self.relativePath = value
    }
    if let value = try container.decodeIfPresent(Swift.Bool.self, forKey: .enableRepairFlag) {
      self.enableRepairFlag = value
    }
    if let value = try container.decodeIfPresent(Swift.Bool.self, forKey: .enablePacketCaptureFlag)
    {
      self.enablePacketCaptureFlag = value
    }
    if let value = try container.decodeIfPresent(Swift.Bool.self, forKey: .enableCopyHomeFilesFlag)
    {
      self.enableCopyHomeFilesFlag = value
    }
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.Value.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.gcsBucket, forKey: .gcsBucket)
    try container.encode(self.relativePath, forKey: .relativePath)
    try container.encode(self.enableRepairFlag, forKey: .enableRepairFlag)
    try container.encode(self.enablePacketCaptureFlag, forKey: .enablePacketCaptureFlag)
    try container.encode(self.enableCopyHomeFilesFlag, forKey: .enableCopyHomeFilesFlag)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.notebooks.v2.DiagnosticConfig"
  }
  public init(fromAny any: GoogleWKT.`Any`) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.Struct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
