// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudWkt

/// The definition of an Event for a managed / semi-managed notebook instance.
public struct Event: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// Optional. Event report time.
  public var reportTime: GoogleCloudWkt.Timestamp? = nil

  /// Optional. Event type.
  public var type: Event.EventType = Event.EventType()

  /// Optional. Event details. This field is used to pass event information.
  public var details: [Swift.String: Swift.String] = [:]

  /// Initialize a new instance of `Event`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = Event().with { $0.reportTime = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  /// The definition of the event types.
  public enum EventType: Codable, Equatable, Sendable {
    /// Event is not specified.
    case unspecified
    /// The instance / runtime is idle
    case idle
    /// The instance / runtime is available.
    /// This event indicates that instance / runtime underlying compute is
    /// operational.
    case heartbeat
    /// The instance / runtime health is available.
    /// This event indicates that instance / runtime health information.
    case health
    /// The instance / runtime is available.
    /// This event allows instance / runtime to send Host maintenance
    /// information to Control Plane.
    /// https://cloud.google.com/compute/docs/gpus/gpu-host-maintenance
    case maintenance
    /// The instance / runtime is available.
    /// This event indicates that the instance had metadata that needs to be
    /// modified.
    case metadataChange
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownStringValue(String)

    public init() {
      self = .unspecified
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .unspecified: return 0
      case .idle: return 1
      case .heartbeat: return 2
      case .health: return 3
      case .maintenance: return 4
      case .metadataChange: return 5
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: Swift.String? {
      switch self {
      case .unspecified: return "EVENT_TYPE_UNSPECIFIED"
      case .idle: return "IDLE"
      case .heartbeat: return "HEARTBEAT"
      case .health: return "HEALTH"
      case .maintenance: return "MAINTENANCE"
      case .metadataChange: return "METADATA_CHANGE"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to ``.unknownStringValue(_:)``.
    public init(stringValue: Swift.String) {
      switch stringValue {
      case "EVENT_TYPE_UNSPECIFIED": self = .unspecified
      case "IDLE": self = .idle
      case "HEARTBEAT": self = .heartbeat
      case "HEALTH": self = .health
      case "MAINTENANCE": self = .maintenance
      case "METADATA_CHANGE": self = .metadataChange
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to ``.unknownIntValue(_:)``.
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .unspecified
      case 1: self = .idle
      case 2: self = .heartbeat
      case 3: self = .health
      case 4: self = .maintenance
      case 5: self = .metadataChange
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .unspecified: return try container.encode(0)
      case .idle: return try container.encode(1)
      case .heartbeat: return try container.encode(2)
      case .health: return try container.encode(3)
      case .maintenance: return try container.encode(4)
      case .metadataChange: return try container.encode(5)
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.notebooks.v2.Event"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
