// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleWKT

/// The definition of how to configure a VM instance outside of Resources and
/// Identity.
public struct GceSetup: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// Optional. The machine type of the VM instance.
  /// https://cloud.google.com/compute/docs/machine-resource
  public var machineType: Swift.String = Swift.String()

  /// Optional. The hardware accelerators used on this instance. If you use
  /// accelerators, make sure that your configuration has
  /// [enough vCPUs and memory to support the `machine_type` you have
  /// selected](https://cloud.google.com/compute/docs/gpus/#gpus-list).
  /// Currently supports only one accelerator configuration.
  public var acceleratorConfigs: [AcceleratorConfig] = []

  /// Optional. The service account that serves as an identity for the VM
  /// instance. Currently supports only one service account.
  public var serviceAccounts: [ServiceAccount] = []

  /// Optional. The boot disk for the VM.
  public var bootDisk: BootDisk? = nil

  /// Optional. Data disks attached to the VM instance.
  /// Currently supports only one data disk.
  public var dataDisks: [DataDisk] = []

  /// Optional. Shielded VM configuration.
  /// [Images using supported Shielded VM
  /// features](https://cloud.google.com/compute/docs/instances/modifying-shielded-vm).
  public var shieldedInstanceConfig: ShieldedInstanceConfig? = nil

  /// Optional. The network interfaces for the VM.
  /// Supports only one interface.
  public var networkInterfaces: [NetworkInterface] = []

  /// Optional. If true, no external IP will be assigned to this VM instance.
  public var disablePublicIp: Swift.Bool = Swift.Bool()

  /// Optional. The Compute Engine tags to add to runtime (see [Tagging
  /// instances](https://cloud.google.com/compute/docs/label-or-tag-resources#tags)).
  public var tags: [Swift.String] = []

  /// Optional. Custom metadata to apply to this instance.
  public var metadata: [Swift.String: Swift.String] = [:]

  /// Optional. Flag to enable ip forwarding or not, default false/off.
  /// https://cloud.google.com/vpc/docs/using-routes#canipforward
  public var enableIpForwarding: Swift.Bool = Swift.Bool()

  /// Optional. Configuration for GPU drivers.
  public var gpuDriverConfig: GPUDriverConfig? = nil

  /// Type of the image; can be one of VM image, or container image.
  public var image: OneOf_Image? = nil

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `GceSetup`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = GceSetup().with { $0.machineType = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let machineType = CodingKeys(stringValue: "machineType")
    static let acceleratorConfigs = CodingKeys(stringValue: "acceleratorConfigs")
    static let serviceAccounts = CodingKeys(stringValue: "serviceAccounts")
    static let vmImage = CodingKeys(stringValue: "vmImage")
    static let containerImage = CodingKeys(stringValue: "containerImage")
    static let bootDisk = CodingKeys(stringValue: "bootDisk")
    static let dataDisks = CodingKeys(stringValue: "dataDisks")
    static let shieldedInstanceConfig = CodingKeys(stringValue: "shieldedInstanceConfig")
    static let networkInterfaces = CodingKeys(stringValue: "networkInterfaces")
    static let disablePublicIp = CodingKeys(stringValue: "disablePublicIp")
    static let tags = CodingKeys(stringValue: "tags")
    static let metadata = CodingKeys(stringValue: "metadata")
    static let enableIpForwarding = CodingKeys(stringValue: "enableIpForwarding")
    static let gpuDriverConfig = CodingKeys(stringValue: "gpuDriverConfig")

    static let _knownKeys: Set<Swift.String> = [
      "machineType",
      "acceleratorConfigs",
      "serviceAccounts",
      "vmImage",
      "containerImage",
      "bootDisk",
      "dataDisks",
      "shieldedInstanceConfig",
      "networkInterfaces",
      "disablePublicIp",
      "tags",
      "metadata",
      "enableIpForwarding",
      "gpuDriverConfig",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .machineType) {
      self.machineType = value
    }
    if let value = try container.decodeIfPresent(
      [AcceleratorConfig].self, forKey: .acceleratorConfigs)
    {
      self.acceleratorConfigs = value
    }
    if let value = try container.decodeIfPresent([ServiceAccount].self, forKey: .serviceAccounts) {
      self.serviceAccounts = value
    }
    self.bootDisk = try container.decodeIfPresent(BootDisk.self, forKey: .bootDisk)
    if let value = try container.decodeIfPresent([DataDisk].self, forKey: .dataDisks) {
      self.dataDisks = value
    }
    self.shieldedInstanceConfig = try container.decodeIfPresent(
      ShieldedInstanceConfig.self, forKey: .shieldedInstanceConfig)
    if let value = try container.decodeIfPresent(
      [NetworkInterface].self, forKey: .networkInterfaces)
    {
      self.networkInterfaces = value
    }
    if let value = try container.decodeIfPresent(Swift.Bool.self, forKey: .disablePublicIp) {
      self.disablePublicIp = value
    }
    if let value = try container.decodeIfPresent([Swift.String].self, forKey: .tags) {
      self.tags = value
    }
    if let value = try container.decodeIfPresent(
      [Swift.String: Swift.String].self, forKey: .metadata)
    {
      self.metadata = value
    }
    if let value = try container.decodeIfPresent(Swift.Bool.self, forKey: .enableIpForwarding) {
      self.enableIpForwarding = value
    }
    self.gpuDriverConfig = try container.decodeIfPresent(
      GPUDriverConfig.self, forKey: .gpuDriverConfig)

    var image: OneOf_Image? = nil
    let imageCheckAndSet = {
      if image != nil {
        throw DecodingError.dataCorrupted(
          DecodingError.Context(
            codingPath: decoder.codingPath,
            debugDescription: "Multiple values set for oneof 'image'"))
      }
      image = $0
    }
    if let vmImage = try container.decodeIfPresent(VmImage?.self, forKey: .vmImage) {
      try imageCheckAndSet(.vmImage(vmImage))
    }
    if let containerImage = try container.decodeIfPresent(
      ContainerImage?.self, forKey: .containerImage)
    {
      try imageCheckAndSet(.containerImage(containerImage))
    }
    self.image = image
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.Value.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.machineType, forKey: .machineType)
    try container.encode(self.acceleratorConfigs, forKey: .acceleratorConfigs)
    try container.encode(self.serviceAccounts, forKey: .serviceAccounts)
    try container.encodeIfPresent(self.bootDisk, forKey: .bootDisk)
    try container.encode(self.dataDisks, forKey: .dataDisks)
    try container.encodeIfPresent(self.shieldedInstanceConfig, forKey: .shieldedInstanceConfig)
    try container.encode(self.networkInterfaces, forKey: .networkInterfaces)
    try container.encode(self.disablePublicIp, forKey: .disablePublicIp)
    try container.encode(self.tags, forKey: .tags)
    try container.encode(self.metadata, forKey: .metadata)
    try container.encode(self.enableIpForwarding, forKey: .enableIpForwarding)
    try container.encodeIfPresent(self.gpuDriverConfig, forKey: .gpuDriverConfig)

    if let choice = self.image {
      switch choice {
      case .vmImage(let value):
        try container.encode(value, forKey: .vmImage)
      case .containerImage(let value):
        try container.encode(value, forKey: .containerImage)
      }
    }
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  /// Type of the image; can be one of VM image, or container image.
  public enum OneOf_Image: Codable, Equatable, Sendable {
    /// Optional. Use a Compute Engine VM image to start the notebook instance.
    indirect case vmImage(VmImage?)
    /// Optional. Use a container image to start the notebook instance.
    indirect case containerImage(ContainerImage?)
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.notebooks.v2.GceSetup"
  }
  public init(fromAny any: GoogleWKT.`Any`) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.Struct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
