// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) public import GoogleWKT

/// The definition of a notebook instance.
public struct Instance: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// Output only. The name of this notebook instance. Format:
  /// `projects/{project_id}/locations/{location}/instances/{instance_id}`
  public var name: Swift.String = Swift.String()

  /// Output only. The proxy endpoint that is used to access the Jupyter
  /// notebook.
  public var proxyUri: Swift.String = Swift.String()

  /// Optional. Input only. The owner of this instance after creation. Format:
  /// `alias@example.com`
  ///
  /// Currently supports one owner only. If not specified, all of the service
  /// account users of your VM instance's service account can use
  /// the instance.
  public var instanceOwners: [Swift.String] = []

  /// Output only. Email address of entity that sent original CreateInstance
  /// request.
  public var creator: Swift.String = Swift.String()

  /// Output only. The state of this instance.
  public var state: State = State()

  /// Output only. The upgrade history of this instance.
  public var upgradeHistory: [UpgradeHistoryEntry] = []

  /// Output only. Unique ID of the resource.
  public var id: Swift.String = Swift.String()

  /// Output only. Instance health_state.
  public var healthState: HealthState = HealthState()

  /// Output only. Additional information about instance health.
  /// Example:
  ///
  ///     healthInfo": {
  ///       "docker_proxy_agent_status": "1",
  ///       "docker_status": "1",
  ///       "jupyterlab_api_status": "-1",
  ///       "jupyterlab_status": "-1",
  ///       "updated": "2020-10-18 09:40:03.573409"
  ///     }
  public var healthInfo: [Swift.String: Swift.String] = [:]

  /// Output only. Instance creation time.
  public var createTime: GoogleWKT.WKTTimestamp? = nil

  /// Output only. Instance update time.
  public var updateTime: GoogleWKT.WKTTimestamp? = nil

  /// Optional. If true, the notebook instance will not register with the proxy.
  public var disableProxyAccess: Swift.Bool = Swift.Bool()

  /// Optional. Labels to apply to this instance.
  /// These can be later modified by the UpdateInstance method.
  public var labels: [Swift.String: Swift.String] = [:]

  /// Setup for the Notebook instance.
  public var infrastructure: OneOf_Infrastructure? = nil

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `Instance`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = Instance().with { $0.name = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let name = CodingKeys(stringValue: "name")
    static let gceSetup = CodingKeys(stringValue: "gceSetup")
    static let proxyUri = CodingKeys(stringValue: "proxyUri")
    static let instanceOwners = CodingKeys(stringValue: "instanceOwners")
    static let creator = CodingKeys(stringValue: "creator")
    static let state = CodingKeys(stringValue: "state")
    static let upgradeHistory = CodingKeys(stringValue: "upgradeHistory")
    static let id = CodingKeys(stringValue: "id")
    static let healthState = CodingKeys(stringValue: "healthState")
    static let healthInfo = CodingKeys(stringValue: "healthInfo")
    static let createTime = CodingKeys(stringValue: "createTime")
    static let updateTime = CodingKeys(stringValue: "updateTime")
    static let disableProxyAccess = CodingKeys(stringValue: "disableProxyAccess")
    static let labels = CodingKeys(stringValue: "labels")

    static let _knownKeys: Set<Swift.String> = [
      "name",
      "gceSetup",
      "proxyUri",
      "instanceOwners",
      "creator",
      "state",
      "upgradeHistory",
      "id",
      "healthState",
      "healthInfo",
      "createTime",
      "updateTime",
      "disableProxyAccess",
      "labels",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .name) {
      self.name = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .proxyUri) {
      self.proxyUri = value
    }
    if let value = try container.decodeIfPresent([Swift.String].self, forKey: .instanceOwners) {
      self.instanceOwners = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .creator) {
      self.creator = value
    }
    if let value = try container.decodeIfPresent(State.self, forKey: .state) {
      self.state = value
    }
    if let value = try container.decodeIfPresent(
      [UpgradeHistoryEntry].self, forKey: .upgradeHistory)
    {
      self.upgradeHistory = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .id) {
      self.id = value
    }
    if let value = try container.decodeIfPresent(HealthState.self, forKey: .healthState) {
      self.healthState = value
    }
    if let value = try container.decodeIfPresent(
      [Swift.String: Swift.String].self, forKey: .healthInfo)
    {
      self.healthInfo = value
    }
    self.createTime = try container.decodeIfPresent(
      GoogleWKT.WKTTimestamp.self, forKey: .createTime)
    self.updateTime = try container.decodeIfPresent(
      GoogleWKT.WKTTimestamp.self, forKey: .updateTime)
    if let value = try container.decodeIfPresent(Swift.Bool.self, forKey: .disableProxyAccess) {
      self.disableProxyAccess = value
    }
    if let value = try container.decodeIfPresent([Swift.String: Swift.String].self, forKey: .labels)
    {
      self.labels = value
    }

    var infrastructure: OneOf_Infrastructure? = nil
    let infrastructureCheckAndSet = {
      if infrastructure != nil {
        throw DecodingError.dataCorrupted(
          DecodingError.Context(
            codingPath: decoder.codingPath,
            debugDescription: "Multiple values set for oneof 'infrastructure'"))
      }
      infrastructure = $0
    }
    if let gceSetup = try container.decodeIfPresent(GceSetup?.self, forKey: .gceSetup) {
      try infrastructureCheckAndSet(.gceSetup(gceSetup))
    }
    self.infrastructure = infrastructure
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.WKTValue.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.name, forKey: .name)
    try container.encode(self.proxyUri, forKey: .proxyUri)
    try container.encode(self.instanceOwners, forKey: .instanceOwners)
    try container.encode(self.creator, forKey: .creator)
    try container.encode(self.state, forKey: .state)
    try container.encode(self.upgradeHistory, forKey: .upgradeHistory)
    try container.encode(self.id, forKey: .id)
    try container.encode(self.healthState, forKey: .healthState)
    try container.encode(self.healthInfo, forKey: .healthInfo)
    try container.encodeIfPresent(self.createTime, forKey: .createTime)
    try container.encodeIfPresent(self.updateTime, forKey: .updateTime)
    try container.encode(self.disableProxyAccess, forKey: .disableProxyAccess)
    try container.encode(self.labels, forKey: .labels)

    if let choice = self.infrastructure {
      switch choice {
      case .gceSetup(let value):
        try container.encode(value, forKey: .gceSetup)
      }
    }
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  /// Setup for the Notebook instance.
  public enum OneOf_Infrastructure: Codable, Equatable, Sendable {
    /// Optional. Compute Engine setup for the notebook. Uses notebook-defined
    /// fields.
    indirect case gceSetup(GceSetup?)
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.notebooks.v2.Instance"
  }
  public init(fromAny any: GoogleWKT.WKTAny) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.WKTStruct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
