// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudWkt

/// Request for listing notebook instances.
public struct ListInstancesRequest: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// Required. Format:
  /// `parent=projects/{project_id}/locations/{location}`
  public var parent: Swift.String = Swift.String()

  /// Optional. Maximum return size of the list call.
  public var pageSize: Swift.Int32 = Swift.Int32()

  /// Optional. A previous returned page token that can be used to continue
  /// listing from the last result.
  public var pageToken: Swift.String = Swift.String()

  /// Optional. Sort results. Supported values are "name", "name desc" or ""
  /// (unsorted).
  public var orderBy: Swift.String = Swift.String()

  /// Optional. List filter.
  public var filter: Swift.String = Swift.String()

  /// Initialize a new instance of `ListInstancesRequest`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = ListInstancesRequest().with { $0.parent = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  public static var _anyTypeUrl: String {
    return "type.googleapis.com/google.cloud.notebooks.v2.ListInstancesRequest"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
