// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
#if canImport(FoundationNetworking)
  import FoundationNetworking
#endif
@_spi(GoogleCloudInternal) public import GoogleCloudLocation
@_spi(GoogleCloudInternal) public import GoogleIAMV1
@_spi(GoogleCloudInternal) public import GoogleLongRunning
@_spi(GoogleCloudInternal) public import GoogleWKT
@_spi(GoogleCloudInternal) public import GoogleGax

/// API v2 service for Workbench Notebooks Instances.
///
/// @Snippet(path: "NotebookServiceQuickstart")
public final class NotebookServiceClient: Clients.NotebookServiceProtocol, Sendable {
  let inner: any Clients.NotebookServiceStub
  let pollingErrorPolicy: GoogleGax.PollingErrorPolicy
  let pollingBackoffPolicy: GoogleGax.BackoffPolicy

  /// Creates a new `NotebookServiceClient` instance.
  public init(_ options: GoogleGax.ClientOptions = .init()) throws {
    var inner: any Clients.NotebookServiceStub = try Clients.NotebookServiceTransport(options)
    inner = Clients.NotebookServiceRetry(inner, options: options)
    if let logger = options.logger {
      inner = Clients.NotebookServiceLogging(inner, logger: logger)
    }
    self.inner = inner
    self.pollingErrorPolicy = options.pollingErrorPolicy
    self.pollingBackoffPolicy = options.pollingBackoffPolicy
  }

  /// Lists instances in a given project and location.
  ///
  /// @Snippet(path: "NotebookService_ListInstances")
  public func listInstances(
    request: ListInstancesRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudNotebooksV2.ListInstancesResponse {
    try await self.inner.listInstances(request: request, options: options)
  }

  /// Gets details of a single Instance.
  ///
  /// @Snippet(path: "NotebookService_GetInstance")
  public func getInstance(
    request: GetInstanceRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudNotebooksV2.Instance {
    try await self.inner.getInstance(request: request, options: options)
  }

  /// Creates a new Instance in a given project and location.
  ///
  /// @Snippet(path: "NotebookService_CreateInstance")
  public func createInstance(
    request: CreateInstanceRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    try await self.inner.createInstance(request: request, options: options)
  }

  /// Creates a new Instance in a given project and location.
  ///
  /// @Snippet(path: "NotebookService_CreateInstance")
  public func createInstancePollingUntilDone(
    request: CreateInstanceRequest, options: GoogleGax.RequestOptions
  ) async throws -> any GoogleGax.PollableOperation<Instance> {
    let extractStatus = {
      (op: GoogleLongRunning.Operation) throws -> GoogleGax._PollableOperationImpl<Instance>.State
      in
      return try op._extractStatus(Instance.self)
    }
    let rawOp = try await self.createInstance(request: request, options: options)
    let initialState = try extractStatus(rawOp)
    let poll = { () async throws -> GoogleGax._PollableOperationImpl<Instance>.State in
      let op = try await self.getOperation(
        request: .init().with { $0.name = rawOp.name }, options: options)
      return try extractStatus(op)
    }
    return GoogleGax._PollableOperationImpl(
      initialState: initialState,
      polling: options.pollingErrorPolicy ?? self.pollingErrorPolicy,
      backoff: options.pollingBackoffPolicy ?? self.pollingBackoffPolicy,
      poll: poll,
    )
  }

  /// UpdateInstance updates an Instance.
  ///
  /// @Snippet(path: "NotebookService_UpdateInstance")
  public func updateInstance(
    request: UpdateInstanceRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    try await self.inner.updateInstance(request: request, options: options)
  }

  /// UpdateInstance updates an Instance.
  ///
  /// @Snippet(path: "NotebookService_UpdateInstance")
  public func updateInstancePollingUntilDone(
    request: UpdateInstanceRequest, options: GoogleGax.RequestOptions
  ) async throws -> any GoogleGax.PollableOperation<Instance> {
    let extractStatus = {
      (op: GoogleLongRunning.Operation) throws -> GoogleGax._PollableOperationImpl<Instance>.State
      in
      return try op._extractStatus(Instance.self)
    }
    let rawOp = try await self.updateInstance(request: request, options: options)
    let initialState = try extractStatus(rawOp)
    let poll = { () async throws -> GoogleGax._PollableOperationImpl<Instance>.State in
      let op = try await self.getOperation(
        request: .init().with { $0.name = rawOp.name }, options: options)
      return try extractStatus(op)
    }
    return GoogleGax._PollableOperationImpl(
      initialState: initialState,
      polling: options.pollingErrorPolicy ?? self.pollingErrorPolicy,
      backoff: options.pollingBackoffPolicy ?? self.pollingBackoffPolicy,
      poll: poll,
    )
  }

  /// Deletes a single Instance.
  ///
  /// @Snippet(path: "NotebookService_DeleteInstance")
  public func deleteInstance(
    request: DeleteInstanceRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    try await self.inner.deleteInstance(request: request, options: options)
  }

  /// Deletes a single Instance.
  ///
  /// @Snippet(path: "NotebookService_DeleteInstance")
  public func deleteInstancePollingUntilDone(
    request: DeleteInstanceRequest, options: GoogleGax.RequestOptions
  ) async throws -> any GoogleGax.PollableOperation<Swift.Void> {
    let extractStatus = {
      (op: GoogleLongRunning.Operation) throws -> GoogleGax._PollableOperationImpl<Swift.Void>.State
      in
      return try op._extractStatusEmpty()
    }
    let rawOp = try await self.deleteInstance(request: request, options: options)
    let initialState = try extractStatus(rawOp)
    let poll = { () async throws -> GoogleGax._PollableOperationImpl<Swift.Void>.State in
      let op = try await self.getOperation(
        request: .init().with { $0.name = rawOp.name }, options: options)
      return try extractStatus(op)
    }
    return GoogleGax._PollableOperationImpl(
      initialState: initialState,
      polling: options.pollingErrorPolicy ?? self.pollingErrorPolicy,
      backoff: options.pollingBackoffPolicy ?? self.pollingBackoffPolicy,
      poll: poll,
    )
  }

  /// Starts a notebook instance.
  ///
  /// @Snippet(path: "NotebookService_StartInstance")
  public func startInstance(
    request: StartInstanceRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    try await self.inner.startInstance(request: request, options: options)
  }

  /// Starts a notebook instance.
  ///
  /// @Snippet(path: "NotebookService_StartInstance")
  public func startInstancePollingUntilDone(
    request: StartInstanceRequest, options: GoogleGax.RequestOptions
  ) async throws -> any GoogleGax.PollableOperation<Instance> {
    let extractStatus = {
      (op: GoogleLongRunning.Operation) throws -> GoogleGax._PollableOperationImpl<Instance>.State
      in
      return try op._extractStatus(Instance.self)
    }
    let rawOp = try await self.startInstance(request: request, options: options)
    let initialState = try extractStatus(rawOp)
    let poll = { () async throws -> GoogleGax._PollableOperationImpl<Instance>.State in
      let op = try await self.getOperation(
        request: .init().with { $0.name = rawOp.name }, options: options)
      return try extractStatus(op)
    }
    return GoogleGax._PollableOperationImpl(
      initialState: initialState,
      polling: options.pollingErrorPolicy ?? self.pollingErrorPolicy,
      backoff: options.pollingBackoffPolicy ?? self.pollingBackoffPolicy,
      poll: poll,
    )
  }

  /// Stops a notebook instance.
  ///
  /// @Snippet(path: "NotebookService_StopInstance")
  public func stopInstance(
    request: StopInstanceRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    try await self.inner.stopInstance(request: request, options: options)
  }

  /// Stops a notebook instance.
  ///
  /// @Snippet(path: "NotebookService_StopInstance")
  public func stopInstancePollingUntilDone(
    request: StopInstanceRequest, options: GoogleGax.RequestOptions
  ) async throws -> any GoogleGax.PollableOperation<Instance> {
    let extractStatus = {
      (op: GoogleLongRunning.Operation) throws -> GoogleGax._PollableOperationImpl<Instance>.State
      in
      return try op._extractStatus(Instance.self)
    }
    let rawOp = try await self.stopInstance(request: request, options: options)
    let initialState = try extractStatus(rawOp)
    let poll = { () async throws -> GoogleGax._PollableOperationImpl<Instance>.State in
      let op = try await self.getOperation(
        request: .init().with { $0.name = rawOp.name }, options: options)
      return try extractStatus(op)
    }
    return GoogleGax._PollableOperationImpl(
      initialState: initialState,
      polling: options.pollingErrorPolicy ?? self.pollingErrorPolicy,
      backoff: options.pollingBackoffPolicy ?? self.pollingBackoffPolicy,
      poll: poll,
    )
  }

  /// Resets a notebook instance.
  ///
  /// @Snippet(path: "NotebookService_ResetInstance")
  public func resetInstance(
    request: ResetInstanceRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    try await self.inner.resetInstance(request: request, options: options)
  }

  /// Resets a notebook instance.
  ///
  /// @Snippet(path: "NotebookService_ResetInstance")
  public func resetInstancePollingUntilDone(
    request: ResetInstanceRequest, options: GoogleGax.RequestOptions
  ) async throws -> any GoogleGax.PollableOperation<Instance> {
    let extractStatus = {
      (op: GoogleLongRunning.Operation) throws -> GoogleGax._PollableOperationImpl<Instance>.State
      in
      return try op._extractStatus(Instance.self)
    }
    let rawOp = try await self.resetInstance(request: request, options: options)
    let initialState = try extractStatus(rawOp)
    let poll = { () async throws -> GoogleGax._PollableOperationImpl<Instance>.State in
      let op = try await self.getOperation(
        request: .init().with { $0.name = rawOp.name }, options: options)
      return try extractStatus(op)
    }
    return GoogleGax._PollableOperationImpl(
      initialState: initialState,
      polling: options.pollingErrorPolicy ?? self.pollingErrorPolicy,
      backoff: options.pollingBackoffPolicy ?? self.pollingBackoffPolicy,
      poll: poll,
    )
  }

  /// Checks whether a notebook instance is upgradable.
  ///
  /// @Snippet(path: "NotebookService_CheckInstanceUpgradability")
  public func checkInstanceUpgradability(
    request: CheckInstanceUpgradabilityRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudNotebooksV2.CheckInstanceUpgradabilityResponse {
    try await self.inner.checkInstanceUpgradability(request: request, options: options)
  }

  /// Upgrades a notebook instance to the latest version.
  ///
  /// @Snippet(path: "NotebookService_UpgradeInstance")
  public func upgradeInstance(
    request: UpgradeInstanceRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    try await self.inner.upgradeInstance(request: request, options: options)
  }

  /// Upgrades a notebook instance to the latest version.
  ///
  /// @Snippet(path: "NotebookService_UpgradeInstance")
  public func upgradeInstancePollingUntilDone(
    request: UpgradeInstanceRequest, options: GoogleGax.RequestOptions
  ) async throws -> any GoogleGax.PollableOperation<Instance> {
    let extractStatus = {
      (op: GoogleLongRunning.Operation) throws -> GoogleGax._PollableOperationImpl<Instance>.State
      in
      return try op._extractStatus(Instance.self)
    }
    let rawOp = try await self.upgradeInstance(request: request, options: options)
    let initialState = try extractStatus(rawOp)
    let poll = { () async throws -> GoogleGax._PollableOperationImpl<Instance>.State in
      let op = try await self.getOperation(
        request: .init().with { $0.name = rawOp.name }, options: options)
      return try extractStatus(op)
    }
    return GoogleGax._PollableOperationImpl(
      initialState: initialState,
      polling: options.pollingErrorPolicy ?? self.pollingErrorPolicy,
      backoff: options.pollingBackoffPolicy ?? self.pollingBackoffPolicy,
      poll: poll,
    )
  }

  /// Rollbacks a notebook instance to the previous version.
  ///
  /// @Snippet(path: "NotebookService_RollbackInstance")
  public func rollbackInstance(
    request: RollbackInstanceRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    try await self.inner.rollbackInstance(request: request, options: options)
  }

  /// Rollbacks a notebook instance to the previous version.
  ///
  /// @Snippet(path: "NotebookService_RollbackInstance")
  public func rollbackInstancePollingUntilDone(
    request: RollbackInstanceRequest, options: GoogleGax.RequestOptions
  ) async throws -> any GoogleGax.PollableOperation<Instance> {
    let extractStatus = {
      (op: GoogleLongRunning.Operation) throws -> GoogleGax._PollableOperationImpl<Instance>.State
      in
      return try op._extractStatus(Instance.self)
    }
    let rawOp = try await self.rollbackInstance(request: request, options: options)
    let initialState = try extractStatus(rawOp)
    let poll = { () async throws -> GoogleGax._PollableOperationImpl<Instance>.State in
      let op = try await self.getOperation(
        request: .init().with { $0.name = rawOp.name }, options: options)
      return try extractStatus(op)
    }
    return GoogleGax._PollableOperationImpl(
      initialState: initialState,
      polling: options.pollingErrorPolicy ?? self.pollingErrorPolicy,
      backoff: options.pollingBackoffPolicy ?? self.pollingBackoffPolicy,
      poll: poll,
    )
  }

  /// Creates a Diagnostic File and runs Diagnostic Tool given an Instance.
  ///
  /// @Snippet(path: "NotebookService_DiagnoseInstance")
  public func diagnoseInstance(
    request: DiagnoseInstanceRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    try await self.inner.diagnoseInstance(request: request, options: options)
  }

  /// Creates a Diagnostic File and runs Diagnostic Tool given an Instance.
  ///
  /// @Snippet(path: "NotebookService_DiagnoseInstance")
  public func diagnoseInstancePollingUntilDone(
    request: DiagnoseInstanceRequest, options: GoogleGax.RequestOptions
  ) async throws -> any GoogleGax.PollableOperation<Instance> {
    let extractStatus = {
      (op: GoogleLongRunning.Operation) throws -> GoogleGax._PollableOperationImpl<Instance>.State
      in
      return try op._extractStatus(Instance.self)
    }
    let rawOp = try await self.diagnoseInstance(request: request, options: options)
    let initialState = try extractStatus(rawOp)
    let poll = { () async throws -> GoogleGax._PollableOperationImpl<Instance>.State in
      let op = try await self.getOperation(
        request: .init().with { $0.name = rawOp.name }, options: options)
      return try extractStatus(op)
    }
    return GoogleGax._PollableOperationImpl(
      initialState: initialState,
      polling: options.pollingErrorPolicy ?? self.pollingErrorPolicy,
      backoff: options.pollingBackoffPolicy ?? self.pollingBackoffPolicy,
      poll: poll,
    )
  }

  /// Lists information about the supported locations for this service.
  ///
  /// @Snippet(path: "NotebookService_ListLocations")
  public func listLocations(
    request: GoogleCloudLocation.ListLocationsRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudLocation.ListLocationsResponse {
    try await self.inner.listLocations(request: request, options: options)
  }

  /// Gets information about a location.
  ///
  /// @Snippet(path: "NotebookService_GetLocation")
  public func getLocation(
    request: GoogleCloudLocation.GetLocationRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudLocation.Location {
    try await self.inner.getLocation(request: request, options: options)
  }

  /// Sets the access control policy on the specified resource. Replaces
  /// any existing policy.
  ///
  /// Can return `NOT_FOUND`, `INVALID_ARGUMENT`, and `PERMISSION_DENIED`
  /// errors.
  ///
  /// @Snippet(path: "NotebookService_SetIamPolicy")
  public func setIamPolicy(
    request: GoogleIAMV1.SetIamPolicyRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleIAMV1.Policy {
    try await self.inner.setIamPolicy(request: request, options: options)
  }

  /// Gets the access control policy for a resource. Returns an empty policy
  /// if the resource exists and does not have a policy set.
  ///
  /// @Snippet(path: "NotebookService_GetIamPolicy")
  public func getIamPolicy(
    request: GoogleIAMV1.GetIamPolicyRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleIAMV1.Policy {
    try await self.inner.getIamPolicy(request: request, options: options)
  }

  /// Returns permissions that a caller has on the specified resource. If the
  /// resource does not exist, this will return an empty set of
  /// permissions, not a `NOT_FOUND` error.
  ///
  /// Note: This operation is designed to be used for building
  /// permission-aware UIs and command-line tools, not for authorization
  /// checking. This operation may "fail open" without warning.
  ///
  /// @Snippet(path: "NotebookService_TestIamPermissions")
  public func testIamPermissions(
    request: GoogleIAMV1.TestIamPermissionsRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleIAMV1.TestIamPermissionsResponse {
    try await self.inner.testIamPermissions(request: request, options: options)
  }

  /// Provides the [Operations][google.longrunning.Operations] service functionality in this service.
  ///
  /// [google.longrunning.Operations]: https://www.google.com/search?q=Swift+google.longrunning+OperationsClient
  ///
  /// @Snippet(path: "NotebookService_ListOperations")
  public func listOperations(
    request: GoogleLongRunning.ListOperationsRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.ListOperationsResponse {
    try await self.inner.listOperations(request: request, options: options)
  }

  /// Provides the [Operations][google.longrunning.Operations] service functionality in this service.
  ///
  /// [google.longrunning.Operations]: https://www.google.com/search?q=Swift+google.longrunning+OperationsClient
  ///
  /// @Snippet(path: "NotebookService_GetOperation")
  func getOperation(
    request: GoogleLongRunning.GetOperationRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    try await self.inner.getOperation(request: request, options: options)
  }

  /// Provides the [Operations][google.longrunning.Operations] service functionality in this service.
  ///
  /// [google.longrunning.Operations]: https://www.google.com/search?q=Swift+google.longrunning+OperationsClient
  ///
  /// @Snippet(path: "NotebookService_DeleteOperation")
  public func deleteOperation(
    request: GoogleLongRunning.DeleteOperationRequest, options: GoogleGax.RequestOptions
  ) async throws {
    try await self.inner.deleteOperation(request: request, options: options)
  }

  /// Provides the [Operations][google.longrunning.Operations] service functionality in this service.
  ///
  /// [google.longrunning.Operations]: https://www.google.com/search?q=Swift+google.longrunning+OperationsClient
  ///
  /// @Snippet(path: "NotebookService_CancelOperation")
  public func cancelOperation(
    request: GoogleLongRunning.CancelOperationRequest, options: GoogleGax.RequestOptions
  ) async throws {
    try await self.inner.cancelOperation(request: request, options: options)
  }
}

extension Clients {
  /// A Swift protocol to mock `NotebookServiceClient`.
  ///
  /// To mock `NotebookServiceClient` change your functions to receive
  /// `some NotebookServiceProtocol` or `any NotebookServiceProtocol`
  /// and pass a mock implementation in your tests.
  public protocol NotebookServiceProtocol: Sendable {
    /// See `NotebookServiceClient.listInstances`.
    func listInstances(
      request: ListInstancesRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudNotebooksV2.ListInstancesResponse

    /// See `NotebookServiceClient.getInstance`.
    func getInstance(
      request: GetInstanceRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudNotebooksV2.Instance

    /// See `NotebookServiceClient.createInstance`.
    func createInstance(
      request: CreateInstanceRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    /// See `NotebookServiceClient.createInstance`.
    func createInstancePollingUntilDone(
      request: CreateInstanceRequest, options: GoogleGax.RequestOptions
    ) async throws -> any GoogleGax.PollableOperation<Instance>

    /// See `NotebookServiceClient.updateInstance`.
    func updateInstance(
      request: UpdateInstanceRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    /// See `NotebookServiceClient.updateInstance`.
    func updateInstancePollingUntilDone(
      request: UpdateInstanceRequest, options: GoogleGax.RequestOptions
    ) async throws -> any GoogleGax.PollableOperation<Instance>

    /// See `NotebookServiceClient.deleteInstance`.
    func deleteInstance(
      request: DeleteInstanceRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    /// See `NotebookServiceClient.deleteInstance`.
    func deleteInstancePollingUntilDone(
      request: DeleteInstanceRequest, options: GoogleGax.RequestOptions
    ) async throws -> any GoogleGax.PollableOperation<Swift.Void>

    /// See `NotebookServiceClient.startInstance`.
    func startInstance(
      request: StartInstanceRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    /// See `NotebookServiceClient.startInstance`.
    func startInstancePollingUntilDone(
      request: StartInstanceRequest, options: GoogleGax.RequestOptions
    ) async throws -> any GoogleGax.PollableOperation<Instance>

    /// See `NotebookServiceClient.stopInstance`.
    func stopInstance(
      request: StopInstanceRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    /// See `NotebookServiceClient.stopInstance`.
    func stopInstancePollingUntilDone(
      request: StopInstanceRequest, options: GoogleGax.RequestOptions
    ) async throws -> any GoogleGax.PollableOperation<Instance>

    /// See `NotebookServiceClient.resetInstance`.
    func resetInstance(
      request: ResetInstanceRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    /// See `NotebookServiceClient.resetInstance`.
    func resetInstancePollingUntilDone(
      request: ResetInstanceRequest, options: GoogleGax.RequestOptions
    ) async throws -> any GoogleGax.PollableOperation<Instance>

    /// See `NotebookServiceClient.checkInstanceUpgradability`.
    func checkInstanceUpgradability(
      request: CheckInstanceUpgradabilityRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudNotebooksV2.CheckInstanceUpgradabilityResponse

    /// See `NotebookServiceClient.upgradeInstance`.
    func upgradeInstance(
      request: UpgradeInstanceRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    /// See `NotebookServiceClient.upgradeInstance`.
    func upgradeInstancePollingUntilDone(
      request: UpgradeInstanceRequest, options: GoogleGax.RequestOptions
    ) async throws -> any GoogleGax.PollableOperation<Instance>

    /// See `NotebookServiceClient.rollbackInstance`.
    func rollbackInstance(
      request: RollbackInstanceRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    /// See `NotebookServiceClient.rollbackInstance`.
    func rollbackInstancePollingUntilDone(
      request: RollbackInstanceRequest, options: GoogleGax.RequestOptions
    ) async throws -> any GoogleGax.PollableOperation<Instance>

    /// See `NotebookServiceClient.diagnoseInstance`.
    func diagnoseInstance(
      request: DiagnoseInstanceRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    /// See `NotebookServiceClient.diagnoseInstance`.
    func diagnoseInstancePollingUntilDone(
      request: DiagnoseInstanceRequest, options: GoogleGax.RequestOptions
    ) async throws -> any GoogleGax.PollableOperation<Instance>

    /// See `NotebookServiceClient.listLocations`.
    func listLocations(
      request: GoogleCloudLocation.ListLocationsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudLocation.ListLocationsResponse

    /// See `NotebookServiceClient.getLocation`.
    func getLocation(
      request: GoogleCloudLocation.GetLocationRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudLocation.Location

    /// See `NotebookServiceClient.setIamPolicy`.
    func setIamPolicy(
      request: GoogleIAMV1.SetIamPolicyRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleIAMV1.Policy

    /// See `NotebookServiceClient.getIamPolicy`.
    func getIamPolicy(
      request: GoogleIAMV1.GetIamPolicyRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleIAMV1.Policy

    /// See `NotebookServiceClient.testIamPermissions`.
    func testIamPermissions(
      request: GoogleIAMV1.TestIamPermissionsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleIAMV1.TestIamPermissionsResponse

    /// See `NotebookServiceClient.listOperations`.
    func listOperations(
      request: GoogleLongRunning.ListOperationsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.ListOperationsResponse

    /// See `NotebookServiceClient.deleteOperation`.
    func deleteOperation(
      request: GoogleLongRunning.DeleteOperationRequest, options: GoogleGax.RequestOptions
    ) async throws

    /// See `NotebookServiceClient.cancelOperation`.
    func cancelOperation(
      request: GoogleLongRunning.CancelOperationRequest, options: GoogleGax.RequestOptions
    ) async throws
  }
}

// Default implementations
extension Clients.NotebookServiceProtocol {
  public func listInstances(request: ListInstancesRequest) async throws
    -> GoogleCloudNotebooksV2.ListInstancesResponse
  {
    try await self.listInstances(request: request, options: .init())
  }

  public func listInstances(
    request: ListInstancesRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudNotebooksV2.ListInstancesResponse {
    throw GoogleGax.RequestError.unimplemented
  }

  public func listInstancesByItems(
    request: ListInstancesRequest
  ) -> any AsyncSequence<Instance, Swift.Error> & Sendable {
    self.listInstancesByItems(request: request, options: .init())
  }

  /// Lists instances in a given project and location.
  ///
  /// @Snippet(path: "NotebookService_ListInstances")
  public func listInstancesByItems(
    request: ListInstancesRequest, options: GoogleGax.RequestOptions
  ) -> any AsyncSequence<Instance, Swift.Error> & Sendable {
    let listRpc = {
      @Sendable (token: Swift.String) async throws -> GoogleCloudNotebooksV2.ListInstancesResponse
      in
      var request = request
      request.pageToken = token
      return try await self.listInstances(request: request, options: options)
    }
    return GoogleGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  public func listInstancesByItems(
    parent: Swift.String,
  ) -> any AsyncSequence<Instance, Swift.Error> & Sendable {
    let request = ListInstancesRequest().with {
      $0.parent = parent
    }
    return self.listInstancesByItems(request: request)
  }

  public func getInstance(request: GetInstanceRequest) async throws
    -> GoogleCloudNotebooksV2.Instance
  {
    try await self.getInstance(request: request, options: .init())
  }

  public func getInstance(
    request: GetInstanceRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudNotebooksV2.Instance {
    throw GoogleGax.RequestError.unimplemented
  }

  public func getInstance(
    name: Swift.String,
  ) async throws -> GoogleCloudNotebooksV2.Instance {
    let request = GetInstanceRequest().with {
      $0.name = name
    }
    return try await self.getInstance(request: request)
  }

  public func createInstance(request: CreateInstanceRequest) async throws
    -> GoogleLongRunning.Operation
  {
    try await self.createInstance(request: request, options: .init())
  }

  public func createInstance(
    request: CreateInstanceRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    throw GoogleGax.RequestError.unimplemented
  }

  public func createInstancePollingUntilDone(request: CreateInstanceRequest) async throws
    -> any GoogleGax.PollableOperation<Instance>
  {
    try await self.createInstancePollingUntilDone(request: request, options: .init())
  }

  public func createInstancePollingUntilDone(
    request: CreateInstanceRequest, options: GoogleGax.RequestOptions
  ) async throws -> any GoogleGax.PollableOperation<Instance> {
    let poll = { () async throws -> GoogleGax._PollableOperationImpl<Instance>.State in
      throw GoogleGax.RequestError.unimplemented
    }
    return GoogleGax._PollableOperationImpl(
      initialState: .init(done: false, result: nil), poll: poll)
  }

  public func createInstancePollingUntilDone(
    parent: Swift.String,
    instance: Instance?,
    instanceId: Swift.String,
  ) async throws -> any GoogleGax.PollableOperation<Instance> {
    let request = CreateInstanceRequest().with {
      $0.parent = parent
      $0.instance = instance
      $0.instanceId = instanceId
    }
    return try await self.createInstancePollingUntilDone(request: request)
  }

  public func updateInstance(request: UpdateInstanceRequest) async throws
    -> GoogleLongRunning.Operation
  {
    try await self.updateInstance(request: request, options: .init())
  }

  public func updateInstance(
    request: UpdateInstanceRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    throw GoogleGax.RequestError.unimplemented
  }

  public func updateInstancePollingUntilDone(request: UpdateInstanceRequest) async throws
    -> any GoogleGax.PollableOperation<Instance>
  {
    try await self.updateInstancePollingUntilDone(request: request, options: .init())
  }

  public func updateInstancePollingUntilDone(
    request: UpdateInstanceRequest, options: GoogleGax.RequestOptions
  ) async throws -> any GoogleGax.PollableOperation<Instance> {
    let poll = { () async throws -> GoogleGax._PollableOperationImpl<Instance>.State in
      throw GoogleGax.RequestError.unimplemented
    }
    return GoogleGax._PollableOperationImpl(
      initialState: .init(done: false, result: nil), poll: poll)
  }

  public func updateInstancePollingUntilDone(
    instance: Instance?,
    updateMask: GoogleWKT.WKTFieldMask?,
  ) async throws -> any GoogleGax.PollableOperation<Instance> {
    let request = UpdateInstanceRequest().with {
      $0.instance = instance
      $0.updateMask = updateMask
    }
    return try await self.updateInstancePollingUntilDone(request: request)
  }

  public func deleteInstance(request: DeleteInstanceRequest) async throws
    -> GoogleLongRunning.Operation
  {
    try await self.deleteInstance(request: request, options: .init())
  }

  public func deleteInstance(
    request: DeleteInstanceRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    throw GoogleGax.RequestError.unimplemented
  }

  public func deleteInstancePollingUntilDone(request: DeleteInstanceRequest) async throws
    -> any GoogleGax.PollableOperation<Swift.Void>
  {
    try await self.deleteInstancePollingUntilDone(request: request, options: .init())
  }

  public func deleteInstancePollingUntilDone(
    request: DeleteInstanceRequest, options: GoogleGax.RequestOptions
  ) async throws -> any GoogleGax.PollableOperation<Swift.Void> {
    let poll = { () async throws -> GoogleGax._PollableOperationImpl<Swift.Void>.State in
      throw GoogleGax.RequestError.unimplemented
    }
    return GoogleGax._PollableOperationImpl(
      initialState: .init(done: false, result: nil), poll: poll)
  }

  public func deleteInstancePollingUntilDone(
    name: Swift.String,
  ) async throws -> any GoogleGax.PollableOperation<Swift.Void> {
    let request = DeleteInstanceRequest().with {
      $0.name = name
    }
    return try await self.deleteInstancePollingUntilDone(request: request)
  }

  public func startInstance(request: StartInstanceRequest) async throws
    -> GoogleLongRunning.Operation
  {
    try await self.startInstance(request: request, options: .init())
  }

  public func startInstance(
    request: StartInstanceRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    throw GoogleGax.RequestError.unimplemented
  }

  public func startInstancePollingUntilDone(request: StartInstanceRequest) async throws
    -> any GoogleGax.PollableOperation<Instance>
  {
    try await self.startInstancePollingUntilDone(request: request, options: .init())
  }

  public func startInstancePollingUntilDone(
    request: StartInstanceRequest, options: GoogleGax.RequestOptions
  ) async throws -> any GoogleGax.PollableOperation<Instance> {
    let poll = { () async throws -> GoogleGax._PollableOperationImpl<Instance>.State in
      throw GoogleGax.RequestError.unimplemented
    }
    return GoogleGax._PollableOperationImpl(
      initialState: .init(done: false, result: nil), poll: poll)
  }

  public func stopInstance(request: StopInstanceRequest) async throws -> GoogleLongRunning.Operation
  {
    try await self.stopInstance(request: request, options: .init())
  }

  public func stopInstance(
    request: StopInstanceRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    throw GoogleGax.RequestError.unimplemented
  }

  public func stopInstancePollingUntilDone(request: StopInstanceRequest) async throws
    -> any GoogleGax.PollableOperation<Instance>
  {
    try await self.stopInstancePollingUntilDone(request: request, options: .init())
  }

  public func stopInstancePollingUntilDone(
    request: StopInstanceRequest, options: GoogleGax.RequestOptions
  ) async throws -> any GoogleGax.PollableOperation<Instance> {
    let poll = { () async throws -> GoogleGax._PollableOperationImpl<Instance>.State in
      throw GoogleGax.RequestError.unimplemented
    }
    return GoogleGax._PollableOperationImpl(
      initialState: .init(done: false, result: nil), poll: poll)
  }

  public func resetInstance(request: ResetInstanceRequest) async throws
    -> GoogleLongRunning.Operation
  {
    try await self.resetInstance(request: request, options: .init())
  }

  public func resetInstance(
    request: ResetInstanceRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    throw GoogleGax.RequestError.unimplemented
  }

  public func resetInstancePollingUntilDone(request: ResetInstanceRequest) async throws
    -> any GoogleGax.PollableOperation<Instance>
  {
    try await self.resetInstancePollingUntilDone(request: request, options: .init())
  }

  public func resetInstancePollingUntilDone(
    request: ResetInstanceRequest, options: GoogleGax.RequestOptions
  ) async throws -> any GoogleGax.PollableOperation<Instance> {
    let poll = { () async throws -> GoogleGax._PollableOperationImpl<Instance>.State in
      throw GoogleGax.RequestError.unimplemented
    }
    return GoogleGax._PollableOperationImpl(
      initialState: .init(done: false, result: nil), poll: poll)
  }

  public func checkInstanceUpgradability(request: CheckInstanceUpgradabilityRequest) async throws
    -> GoogleCloudNotebooksV2.CheckInstanceUpgradabilityResponse
  {
    try await self.checkInstanceUpgradability(request: request, options: .init())
  }

  public func checkInstanceUpgradability(
    request: CheckInstanceUpgradabilityRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudNotebooksV2.CheckInstanceUpgradabilityResponse {
    throw GoogleGax.RequestError.unimplemented
  }

  public func upgradeInstance(request: UpgradeInstanceRequest) async throws
    -> GoogleLongRunning.Operation
  {
    try await self.upgradeInstance(request: request, options: .init())
  }

  public func upgradeInstance(
    request: UpgradeInstanceRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    throw GoogleGax.RequestError.unimplemented
  }

  public func upgradeInstancePollingUntilDone(request: UpgradeInstanceRequest) async throws
    -> any GoogleGax.PollableOperation<Instance>
  {
    try await self.upgradeInstancePollingUntilDone(request: request, options: .init())
  }

  public func upgradeInstancePollingUntilDone(
    request: UpgradeInstanceRequest, options: GoogleGax.RequestOptions
  ) async throws -> any GoogleGax.PollableOperation<Instance> {
    let poll = { () async throws -> GoogleGax._PollableOperationImpl<Instance>.State in
      throw GoogleGax.RequestError.unimplemented
    }
    return GoogleGax._PollableOperationImpl(
      initialState: .init(done: false, result: nil), poll: poll)
  }

  public func rollbackInstance(request: RollbackInstanceRequest) async throws
    -> GoogleLongRunning.Operation
  {
    try await self.rollbackInstance(request: request, options: .init())
  }

  public func rollbackInstance(
    request: RollbackInstanceRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    throw GoogleGax.RequestError.unimplemented
  }

  public func rollbackInstancePollingUntilDone(request: RollbackInstanceRequest) async throws
    -> any GoogleGax.PollableOperation<Instance>
  {
    try await self.rollbackInstancePollingUntilDone(request: request, options: .init())
  }

  public func rollbackInstancePollingUntilDone(
    request: RollbackInstanceRequest, options: GoogleGax.RequestOptions
  ) async throws -> any GoogleGax.PollableOperation<Instance> {
    let poll = { () async throws -> GoogleGax._PollableOperationImpl<Instance>.State in
      throw GoogleGax.RequestError.unimplemented
    }
    return GoogleGax._PollableOperationImpl(
      initialState: .init(done: false, result: nil), poll: poll)
  }

  public func diagnoseInstance(request: DiagnoseInstanceRequest) async throws
    -> GoogleLongRunning.Operation
  {
    try await self.diagnoseInstance(request: request, options: .init())
  }

  public func diagnoseInstance(
    request: DiagnoseInstanceRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    throw GoogleGax.RequestError.unimplemented
  }

  public func diagnoseInstancePollingUntilDone(request: DiagnoseInstanceRequest) async throws
    -> any GoogleGax.PollableOperation<Instance>
  {
    try await self.diagnoseInstancePollingUntilDone(request: request, options: .init())
  }

  public func diagnoseInstancePollingUntilDone(
    request: DiagnoseInstanceRequest, options: GoogleGax.RequestOptions
  ) async throws -> any GoogleGax.PollableOperation<Instance> {
    let poll = { () async throws -> GoogleGax._PollableOperationImpl<Instance>.State in
      throw GoogleGax.RequestError.unimplemented
    }
    return GoogleGax._PollableOperationImpl(
      initialState: .init(done: false, result: nil), poll: poll)
  }

  public func diagnoseInstancePollingUntilDone(
    name: Swift.String,
    diagnosticConfig: DiagnosticConfig?,
  ) async throws -> any GoogleGax.PollableOperation<Instance> {
    let request = DiagnoseInstanceRequest().with {
      $0.name = name
      $0.diagnosticConfig = diagnosticConfig
    }
    return try await self.diagnoseInstancePollingUntilDone(request: request)
  }

  public func listLocations(request: GoogleCloudLocation.ListLocationsRequest) async throws
    -> GoogleCloudLocation.ListLocationsResponse
  {
    try await self.listLocations(request: request, options: .init())
  }

  public func listLocations(
    request: GoogleCloudLocation.ListLocationsRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudLocation.ListLocationsResponse {
    throw GoogleGax.RequestError.unimplemented
  }

  public func listLocationsByItems(
    request: GoogleCloudLocation.ListLocationsRequest
  ) -> any AsyncSequence<GoogleCloudLocation.Location, Swift.Error> & Sendable {
    self.listLocationsByItems(request: request, options: .init())
  }

  /// Lists information about the supported locations for this service.
  ///
  /// @Snippet(path: "NotebookService_ListLocations")
  public func listLocationsByItems(
    request: GoogleCloudLocation.ListLocationsRequest, options: GoogleGax.RequestOptions
  ) -> any AsyncSequence<GoogleCloudLocation.Location, Swift.Error> & Sendable {
    let listRpc = {
      @Sendable (token: Swift.String) async throws -> GoogleCloudLocation.ListLocationsResponse in
      var request = request
      request.pageToken = token
      return try await self.listLocations(request: request, options: options)
    }
    return GoogleGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  public func getLocation(request: GoogleCloudLocation.GetLocationRequest) async throws
    -> GoogleCloudLocation.Location
  {
    try await self.getLocation(request: request, options: .init())
  }

  public func getLocation(
    request: GoogleCloudLocation.GetLocationRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudLocation.Location {
    throw GoogleGax.RequestError.unimplemented
  }

  public func setIamPolicy(request: GoogleIAMV1.SetIamPolicyRequest) async throws
    -> GoogleIAMV1.Policy
  {
    try await self.setIamPolicy(request: request, options: .init())
  }

  public func setIamPolicy(
    request: GoogleIAMV1.SetIamPolicyRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleIAMV1.Policy {
    throw GoogleGax.RequestError.unimplemented
  }

  public func getIamPolicy(request: GoogleIAMV1.GetIamPolicyRequest) async throws
    -> GoogleIAMV1.Policy
  {
    try await self.getIamPolicy(request: request, options: .init())
  }

  public func getIamPolicy(
    request: GoogleIAMV1.GetIamPolicyRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleIAMV1.Policy {
    throw GoogleGax.RequestError.unimplemented
  }

  public func testIamPermissions(request: GoogleIAMV1.TestIamPermissionsRequest) async throws
    -> GoogleIAMV1.TestIamPermissionsResponse
  {
    try await self.testIamPermissions(request: request, options: .init())
  }

  public func testIamPermissions(
    request: GoogleIAMV1.TestIamPermissionsRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleIAMV1.TestIamPermissionsResponse {
    throw GoogleGax.RequestError.unimplemented
  }

  public func listOperations(request: GoogleLongRunning.ListOperationsRequest) async throws
    -> GoogleLongRunning.ListOperationsResponse
  {
    try await self.listOperations(request: request, options: .init())
  }

  public func listOperations(
    request: GoogleLongRunning.ListOperationsRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.ListOperationsResponse {
    throw GoogleGax.RequestError.unimplemented
  }

  public func listOperationsByItems(
    request: GoogleLongRunning.ListOperationsRequest
  ) -> any AsyncSequence<GoogleLongRunning.Operation, Swift.Error> & Sendable {
    self.listOperationsByItems(request: request, options: .init())
  }

  /// Provides the [Operations][google.longrunning.Operations] service functionality in this service.
  ///
  /// [google.longrunning.Operations]: https://www.google.com/search?q=Swift+google.longrunning+OperationsClient
  ///
  /// @Snippet(path: "NotebookService_ListOperations")
  public func listOperationsByItems(
    request: GoogleLongRunning.ListOperationsRequest, options: GoogleGax.RequestOptions
  ) -> any AsyncSequence<GoogleLongRunning.Operation, Swift.Error> & Sendable {
    let listRpc = {
      @Sendable (token: Swift.String) async throws -> GoogleLongRunning.ListOperationsResponse in
      var request = request
      request.pageToken = token
      return try await self.listOperations(request: request, options: options)
    }
    return GoogleGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  public func listOperationsByItems(
    name: Swift.String,
    filter: Swift.String,
  ) -> any AsyncSequence<GoogleLongRunning.Operation, Swift.Error> & Sendable {
    let request = GoogleLongRunning.ListOperationsRequest().with {
      $0.name = name
      $0.filter = filter
    }
    return self.listOperationsByItems(request: request)
  }

  public func getOperation(request: GoogleLongRunning.GetOperationRequest) async throws
    -> GoogleLongRunning.Operation
  {
    try await self.getOperation(request: request, options: .init())
  }

  public func getOperation(
    request: GoogleLongRunning.GetOperationRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    throw GoogleGax.RequestError.unimplemented
  }

  public func getOperation(
    name: Swift.String,
  ) async throws -> GoogleLongRunning.Operation {
    let request = GoogleLongRunning.GetOperationRequest().with {
      $0.name = name
    }
    return try await self.getOperation(request: request)
  }

  public func deleteOperation(request: GoogleLongRunning.DeleteOperationRequest) async throws {
    try await self.deleteOperation(request: request, options: .init())
  }

  public func deleteOperation(
    request: GoogleLongRunning.DeleteOperationRequest, options: GoogleGax.RequestOptions
  ) async throws {
    throw GoogleGax.RequestError.unimplemented
  }

  public func deleteOperation(
    name: Swift.String,
  ) async throws {
    let request = GoogleLongRunning.DeleteOperationRequest().with {
      $0.name = name
    }
    try await self.deleteOperation(request: request)
  }

  public func cancelOperation(request: GoogleLongRunning.CancelOperationRequest) async throws {
    try await self.cancelOperation(request: request, options: .init())
  }

  public func cancelOperation(
    request: GoogleLongRunning.CancelOperationRequest, options: GoogleGax.RequestOptions
  ) async throws {
    throw GoogleGax.RequestError.unimplemented
  }

  public func cancelOperation(
    name: Swift.String,
  ) async throws {
    let request = GoogleLongRunning.CancelOperationRequest().with {
      $0.name = name
    }
    try await self.cancelOperation(request: request)
  }
}
