// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation

/// The definition of the states of this instance.
public enum State: Codable, Equatable, Sendable {
  /// State is not specified.
  case unspecified
  /// The control logic is starting the instance.
  case starting
  /// The control logic is installing required frameworks and registering the
  /// instance with notebook proxy
  case provisioning
  /// The instance is running.
  case active
  /// The control logic is stopping the instance.
  case stopping
  /// The instance is stopped.
  case stopped
  /// The instance is deleted.
  case deleted
  /// The instance is upgrading.
  case upgrading
  /// The instance is being created.
  case initializing
  /// The instance is suspending.
  case suspending
  /// The instance is suspended.
  case suspended
  /// Encodes an unknown integer value.
  ///
  /// The most common cause for an unknown values is for the service to send
  /// a value unknown to the library. We recommend you update your library to
  /// the latest version.
  case unknownIntValue(Int)
  /// Encodes an unknown string value.
  ///
  /// The most common cause for an unknown values is for the service to send
  /// a value unknown to the library. We recommend you update your library to
  /// the latest version.
  case unknownStringValue(String)

  public init() {
    self = .unspecified
  }

  /// Returns the integer value associated with the enumeration.
  ///
  /// If the enumeration was initialized with an unknown string value, this returns `nil`.
  public var intValue: Int? {
    switch self {
    case .unspecified: return 0
    case .starting: return 1
    case .provisioning: return 2
    case .active: return 3
    case .stopping: return 4
    case .stopped: return 5
    case .deleted: return 6
    case .upgrading: return 7
    case .initializing: return 8
    case .suspending: return 9
    case .suspended: return 10
    case .unknownIntValue(let v): return v
    case .unknownStringValue: return nil
    }
  }

  /// Returns the string value (or name) associated with the enumeration.
  ///
  /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
  public var stringValue: Swift.String? {
    switch self {
    case .unspecified: return "STATE_UNSPECIFIED"
    case .starting: return "STARTING"
    case .provisioning: return "PROVISIONING"
    case .active: return "ACTIVE"
    case .stopping: return "STOPPING"
    case .stopped: return "STOPPED"
    case .deleted: return "DELETED"
    case .upgrading: return "UPGRADING"
    case .initializing: return "INITIALIZING"
    case .suspending: return "SUSPENDING"
    case .suspended: return "SUSPENDED"
    case .unknownIntValue: return nil
    case .unknownStringValue(let v): return v
    }
  }

  /// Initialize from a string value.
  ///
  /// If the value is unknown, this initializes to ``.unknownStringValue(_:)``.
  public init(stringValue: Swift.String) {
    switch stringValue {
    case "STATE_UNSPECIFIED": self = .unspecified
    case "STARTING": self = .starting
    case "PROVISIONING": self = .provisioning
    case "ACTIVE": self = .active
    case "STOPPING": self = .stopping
    case "STOPPED": self = .stopped
    case "DELETED": self = .deleted
    case "UPGRADING": self = .upgrading
    case "INITIALIZING": self = .initializing
    case "SUSPENDING": self = .suspending
    case "SUSPENDED": self = .suspended
    default: self = .unknownStringValue(stringValue)
    }
  }

  /// Initialize from an integer value.
  ///
  /// If the value is unknown, this initializes to ``.unknownIntValue(_:)``.
  public init(intValue: Int) {
    switch intValue {
    case 0: self = .unspecified
    case 1: self = .starting
    case 2: self = .provisioning
    case 3: self = .active
    case 4: self = .stopping
    case 5: self = .stopped
    case 6: self = .deleted
    case 7: self = .upgrading
    case 8: self = .initializing
    case 9: self = .suspending
    case 10: self = .suspended
    default: self = .unknownIntValue(intValue)
    }
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.singleValueContainer()
    if let v = try? container.decode(Int.self) {
      self.init(intValue: v)
      return
    }
    if let s = try? container.decode(String.self) {
      if let v = Int(s) {
        self.init(intValue: v)
      } else {
        self.init(stringValue: s)
      }
      return
    }
    throw DecodingError.dataCorruptedError(
      in: container, debugDescription: "Expected enum value, must be integer or string.")
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.singleValueContainer()
    switch self {
    case .unspecified: return try container.encode(0)
    case .starting: return try container.encode(1)
    case .provisioning: return try container.encode(2)
    case .active: return try container.encode(3)
    case .stopping: return try container.encode(4)
    case .stopped: return try container.encode(5)
    case .deleted: return try container.encode(6)
    case .upgrading: return try container.encode(7)
    case .initializing: return try container.encode(8)
    case .suspending: return try container.encode(9)
    case .suspended: return try container.encode(10)
    case .unknownIntValue(let v): return try container.encode(v)
    case .unknownStringValue(let v): return try container.encode(v)
    }
  }
}
