// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) public import GoogleWKT

/// The entry of VM image upgrade history.
public struct UpgradeHistoryEntry: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// Optional. The snapshot of the boot disk of this notebook instance before
  /// upgrade.
  public var snapshot: Swift.String = Swift.String()

  /// Optional. The VM image before this instance upgrade.
  public var vmImage: Swift.String = Swift.String()

  /// Optional. The container image before this instance upgrade.
  public var containerImage: Swift.String = Swift.String()

  /// Optional. The framework of this notebook instance.
  public var framework: Swift.String = Swift.String()

  /// Optional. The version of the notebook instance before this upgrade.
  public var version: Swift.String = Swift.String()

  /// Output only. The state of this instance upgrade history entry.
  public var state: UpgradeHistoryEntry.State = UpgradeHistoryEntry.State()

  /// Immutable. The time that this instance upgrade history entry is created.
  public var createTime: GoogleWKT.WKTTimestamp? = nil

  /// Optional. Action. Rolloback or Upgrade.
  public var action: UpgradeHistoryEntry.Action = UpgradeHistoryEntry.Action()

  /// Optional. Target VM Version, like m63.
  public var targetVersion: Swift.String = Swift.String()

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `UpgradeHistoryEntry`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = UpgradeHistoryEntry().with { $0.snapshot = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let snapshot = CodingKeys(stringValue: "snapshot")
    static let vmImage = CodingKeys(stringValue: "vmImage")
    static let containerImage = CodingKeys(stringValue: "containerImage")
    static let framework = CodingKeys(stringValue: "framework")
    static let version = CodingKeys(stringValue: "version")
    static let state = CodingKeys(stringValue: "state")
    static let createTime = CodingKeys(stringValue: "createTime")
    static let action = CodingKeys(stringValue: "action")
    static let targetVersion = CodingKeys(stringValue: "targetVersion")

    static let _knownKeys: Set<Swift.String> = [
      "snapshot",
      "vmImage",
      "containerImage",
      "framework",
      "version",
      "state",
      "createTime",
      "action",
      "targetVersion",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .snapshot) {
      self.snapshot = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .vmImage) {
      self.vmImage = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .containerImage) {
      self.containerImage = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .framework) {
      self.framework = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .version) {
      self.version = value
    }
    if let value = try container.decodeIfPresent(UpgradeHistoryEntry.State.self, forKey: .state) {
      self.state = value
    }
    self.createTime = try container.decodeIfPresent(
      GoogleWKT.WKTTimestamp.self, forKey: .createTime)
    if let value = try container.decodeIfPresent(UpgradeHistoryEntry.Action.self, forKey: .action) {
      self.action = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .targetVersion) {
      self.targetVersion = value
    }
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.WKTValue.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.snapshot, forKey: .snapshot)
    try container.encode(self.vmImage, forKey: .vmImage)
    try container.encode(self.containerImage, forKey: .containerImage)
    try container.encode(self.framework, forKey: .framework)
    try container.encode(self.version, forKey: .version)
    try container.encode(self.state, forKey: .state)
    try container.encodeIfPresent(self.createTime, forKey: .createTime)
    try container.encode(self.action, forKey: .action)
    try container.encode(self.targetVersion, forKey: .targetVersion)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  /// The definition of the states of this upgrade history entry.
  ///
  /// - Note: Adding cases to this enumeration is not considered a breaking change.
  ///   Always include an `@unknown default:` case when switching over this type.
  ///   Do not pattern-match against `unknownStringValue` or `unknownIntValue`
  ///   expecting specific values to remain unparsed; future releases may promote
  ///   them to named cases.
  public enum State: Codable, Equatable, Hashable, Sendable {
    /// State is not specified.
    case unspecified
    /// The instance upgrade is started.
    case started
    /// The instance upgrade is succeeded.
    case succeeded
    /// The instance upgrade is failed.
    case failed
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown value is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    ///
    /// - Warning: Do not pattern-match specific integer values in this case;
    ///   future releases may promote them to named enum cases.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown value is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    ///
    /// - Warning: Do not pattern-match specific string literals in this case;
    ///   future releases may promote them to named enum cases.
    case unknownStringValue(String)

    public init() {
      self = .unspecified
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .unspecified: return 0
      case .started: return 1
      case .succeeded: return 2
      case .failed: return 3
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: Swift.String? {
      switch self {
      case .unspecified: return "STATE_UNSPECIFIED"
      case .started: return "STARTED"
      case .succeeded: return "SUCCEEDED"
      case .failed: return "FAILED"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to [`unknownStringValue`](doc:State/unknownStringValue(_:)).
    public init(stringValue: Swift.String) {
      switch stringValue {
      case "STATE_UNSPECIFIED": self = .unspecified
      case "STARTED": self = .started
      case "SUCCEEDED": self = .succeeded
      case "FAILED": self = .failed
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to [`unknownIntValue`](doc:State/unknownIntValue(_:)).
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .unspecified
      case 1: self = .started
      case 2: self = .succeeded
      case 3: self = .failed
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .unspecified: return try container.encode("STATE_UNSPECIFIED")
      case .started: return try container.encode("STARTED")
      case .succeeded: return try container.encode("SUCCEEDED")
      case .failed: return try container.encode("FAILED")
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  /// The definition of operations of this upgrade history entry.
  ///
  /// - Note: Adding cases to this enumeration is not considered a breaking change.
  ///   Always include an `@unknown default:` case when switching over this type.
  ///   Do not pattern-match against `unknownStringValue` or `unknownIntValue`
  ///   expecting specific values to remain unparsed; future releases may promote
  ///   them to named cases.
  public enum Action: Codable, Equatable, Hashable, Sendable {
    /// Operation is not specified.
    case unspecified
    /// Upgrade.
    case upgrade
    /// Rollback.
    case rollback
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown value is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    ///
    /// - Warning: Do not pattern-match specific integer values in this case;
    ///   future releases may promote them to named enum cases.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown value is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    ///
    /// - Warning: Do not pattern-match specific string literals in this case;
    ///   future releases may promote them to named enum cases.
    case unknownStringValue(String)

    public init() {
      self = .unspecified
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .unspecified: return 0
      case .upgrade: return 1
      case .rollback: return 2
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: Swift.String? {
      switch self {
      case .unspecified: return "ACTION_UNSPECIFIED"
      case .upgrade: return "UPGRADE"
      case .rollback: return "ROLLBACK"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to [`unknownStringValue`](doc:Action/unknownStringValue(_:)).
    public init(stringValue: Swift.String) {
      switch stringValue {
      case "ACTION_UNSPECIFIED": self = .unspecified
      case "UPGRADE": self = .upgrade
      case "ROLLBACK": self = .rollback
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to [`unknownIntValue`](doc:Action/unknownIntValue(_:)).
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .unspecified
      case 1: self = .upgrade
      case 2: self = .rollback
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .unspecified: return try container.encode("ACTION_UNSPECIFIED")
      case .upgrade: return try container.encode("UPGRADE")
      case .rollback: return try container.encode("ROLLBACK")
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.notebooks.v2.UpgradeHistoryEntry"
  }
  public init(fromAny any: GoogleWKT.WKTAny) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.WKTStruct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
