// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) public import GoogleWKT

/// Definition of a custom Compute Engine virtual machine image for starting a
/// notebook instance with the environment installed directly on the VM.
public struct VmImage: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// Required. The name of the Google Cloud project that this VM image belongs
  /// to. Format: `{project_id}`
  public var project: Swift.String = Swift.String()

  /// The reference to an external Compute Engine VM image.
  public var image: OneOf_Image? = nil

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `VmImage`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = VmImage().with { $0.project = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let project = CodingKeys(stringValue: "project")
    static let name = CodingKeys(stringValue: "name")
    static let family = CodingKeys(stringValue: "family")

    static let _knownKeys: Set<Swift.String> = [
      "project",
      "name",
      "family",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .project) {
      self.project = value
    }

    var image: OneOf_Image? = nil
    let imageCheckAndSet = {
      if image != nil {
        throw DecodingError.dataCorrupted(
          DecodingError.Context(
            codingPath: decoder.codingPath,
            debugDescription: "Multiple values set for oneof 'image'"))
      }
      image = $0
    }
    if let name = try container.decodeIfPresent(Swift.String.self, forKey: .name) {
      try imageCheckAndSet(.name(name))
    }
    if let family = try container.decodeIfPresent(Swift.String.self, forKey: .family) {
      try imageCheckAndSet(.family(family))
    }
    self.image = image
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.WKTValue.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.project, forKey: .project)

    if let choice = self.image {
      switch choice {
      case .name(let value):
        try container.encode(value, forKey: .name)
      case .family(let value):
        try container.encode(value, forKey: .family)
      }
    }
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  /// The reference to an external Compute Engine VM image.
  public enum OneOf_Image: Codable, Equatable, Sendable {
    /// Optional. Use VM image name to find the image.
    case name(Swift.String)
    /// Optional. Use this VM image family to find the image; the newest image in
    /// this family will be used.
    case family(Swift.String)
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.notebooks.v2.VmImage"
  }
  public init(fromAny any: GoogleWKT.WKTAny) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.WKTStruct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
